# Circle CI 2.0 Config File
# This config file will prevent tests from being run on the gh-pages branch.
version: 2
jobs:
  noop:
    docker:
      - image: node:latest
    steps:
      - run: echo "no tests on this branch"

workflows:
  version: 2
  noop:
    jobs:
      - noop
