version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "alm-cli@salesforce.com"
            git config --global user.name "SF-CLI-BOT"
            echo "machine github.com login SF-CLI-BOT password $GH_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=SF-CLI-BOT yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              only:
                - docs
