version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - uses: salesforcecli/github-workflows/.github/actions/gitConfig@main
      - run:
          name: Deploying to GitHub Pages
          command: |
            cd website && yarn install && yarn build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          context: SF-CLI-RELEASE-PROCESS
          filters:
            branches:
              only:
                - docs
