# test
name: build-docs

on:
  push:
    branches: [docs]

jobs:
  docs:
    defaults:
      run:
        working-directory: website
    env:
      GITHUB_TOKEN: ${{ secrets.SF_CLI_BOT_GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SF_CLI_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: oclif/github-workflows/.github/actions/gitConfig@main
      - name: build docs
        run: |
          rm -rf website/build
          git worktree prune
          git fetch origin gh-pages:gh-pages
          git worktree add website/build gh-pages
      - name: send to git
        run: |
          git add website/build
          git commit -m 'docs: publishing gh-pages [skip ci]' --no-verify
          git push origin gh-pages --no-verify
